[versions]
asm = "9.7.1"
configurate = "4.1.2"
junit = "5.10.2"
kotlin = "2.1.0"
log4j = "2.24.2"

[libraries]
annotations = "org.jetbrains:annotations:24.1.0"
apiguardian = "org.apiguardian:apiguardian-api:1.1.2"
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
asm-util = { module = "org.ow2.asm:asm-util", version.ref = "asm" }
clikt = "com.github.ajalt.clikt:clikt:4.4.0"
configurate-core = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-kotlin = { module = "org.spongepowered:configurate-extra-kotlin", version.ref = "configurate" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0"
csv = "org.apache.commons:commons-csv:1.12.0"
guice = "com.google.inject:guice:5.1.0"
jansi = "org.fusesource.jansi:jansi:2.4.1"
junit-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-launcher = "org.junit.platform:junit-platform-launcher:1.10.2"
juniversalchardet = "com.github.albfernandez:juniversalchardet:2.5.0"
logging-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
logging-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

[bundles]
junit = ["junit-core", "junit-engine", "junit-launcher"]

[plugins]
download = "de.undercouch.download:5.6.0"
gradle-publish = "com.gradle.plugin-publish:1.3.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
style = "org.sourcegrade.style:3.0.0"
